#!/usr/bin/env python3
"""pe2h.py -- embed a PE32+ image as a C byte-array header for the kernel loader.

Usage: python tools/pe2h.py <input.exe|dll> <symbol_name> <output.h>

Emits, matching the existing kernel/ldr/*_pe.h convention:
    static const u8    s_<name>_pe[]        = { ... };
    static const usize s_<name>_pe_size     = sizeof(...);
    static const u64   s_<name>_image_base  = 0x...ULL;   // from the PE header
"""
import struct
import sys


def main():
    if len(sys.argv) != 4:
        print("usage: pe2h.py <input> <name> <output.h>", file=sys.stderr)
        return 2
    inp, name, out = sys.argv[1], sys.argv[2], sys.argv[3]
    data = open(inp, "rb").read()
    if data[:2] != b"MZ":
        print("not an MZ image", file=sys.stderr)
        return 1
    e_lfanew = struct.unpack_from("<I", data, 0x3C)[0]
    if data[e_lfanew:e_lfanew + 2] != b"PE":
        print("not a PE image", file=sys.stderr)
        return 1
    opt = e_lfanew + 24
    magic = struct.unpack_from("<H", data, opt)[0]
    if magic != 0x20B:
        print("not PE32+ (magic 0x%X)" % magic, file=sys.stderr)
        return 1
    image_base = struct.unpack_from("<Q", data, opt + 24)[0]

    with open(out, "w", newline="\n") as f:
        f.write(f"// {name}_pe.h -- auto-generated by tools/pe2h.py. Do not edit.\n")
        f.write("#pragma once\n#include \"../include/ntdef.h\"\n\n")
        f.write(f"static const u8 s_{name}_pe[] = {{\n")
        for i in range(0, len(data), 16):
            row = data[i:i + 16]
            f.write("    " + ",".join(f"0x{b:02X}" for b in row) + ",\n")
        f.write("};\n")
        f.write(f"static const usize s_{name}_pe_size = sizeof(s_{name}_pe);\n")
        f.write(f"static const u64 s_{name}_image_base = 0x{image_base:X}ULL;\n")
    print(f"[pe2h] {inp} ({len(data)} bytes, base 0x{image_base:X}) -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
