#!/usr/bin/env python3
"""svg2icons.py -- rasterize free SVG icons into an embedded C alpha-mask header.

Source icons: Microsoft "Fluent System Icons" (MIT License), fetched into
assets/icons/.  Each SVG is rasterized with ImageMagick, reduced to an 8-bit
coverage (alpha) mask with Pillow, and emitted as a C array.  The kernel then
composites each mask in a chosen color onto a themed desktop tile, so the same
glyph works for any accent/gloss the shell theme picks.

Usage:  python tools/svg2icons.py
Outputs: kernel/include/desktop_icons.h

Requires: ImageMagick ('magick' on PATH) and Pillow.
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "icons")
OUT = os.path.join(ROOT, "kernel", "include", "desktop_icons.h")

ICON_W = 44
ICON_H = 44
SUPERSAMPLE = 2  # render at 2x then box-down for crisp coverage

# Order MUST match DESKTOPMODEL::IconKind (Computer, Folder, Network,
# Media, Control, Recycle).
ICONS = [
    ("COMPUTER", "computer.svg"),
    ("FOLDER", "folder.svg"),
    ("NETWORK", "network.svg"),
    ("MEDIA", "media.svg"),
    ("CONTROL", "control.svg"),
    ("RECYCLE", "recycle.svg"),
]


def rasterize(svg_path):
    from PIL import Image

    png = svg_path + ".png"
    big = max(ICON_W, ICON_H) * SUPERSAMPLE
    # MSVG/RSVG rasterization with transparent background.
    subprocess.run(
        ["magick", "-background", "none", "-density", "384", svg_path,
         "-resize", f"{big}x{big}", png],
        check=True,
    )
    im = Image.open(png).convert("RGBA").resize((ICON_W, ICON_H), Image.LANCZOS)
    os.remove(png)
    # Coverage = alpha channel (Fluent filled glyphs are a solid silhouette).
    return im.getchannel("A").tobytes()


def emit(arrays):
    lines = []
    lines.append("// desktop_icons.h -- GENERATED by tools/svg2icons.py. Do not edit.")
    lines.append("//")
    lines.append("// Glyph coverage (alpha) masks derived from Microsoft Fluent System")
    lines.append("// Icons (MIT License). Each mask is composited in a theme color by the")
    lines.append("// shell renderer. See assets/icons/LICENSE.txt for attribution.")
    lines.append("#pragma once")
    lines.append("")
    lines.append(f"#define DESKTOP_ICON_W {ICON_W}")
    lines.append(f"#define DESKTOP_ICON_H {ICON_H}")
    lines.append("")
    names = []
    for name, data in arrays:
        names.append(name)
        lines.append(f"static const unsigned char ICON_{name}[{ICON_W * ICON_H}] = {{")
        for r in range(ICON_H):
            row = data[r * ICON_W:(r + 1) * ICON_W]
            lines.append("    " + ",".join(str(b) for b in row) + ",")
        lines.append("};")
        lines.append("")
    lines.append(f"static const unsigned char* const DESKTOP_ICON_ALPHA[{len(names)}] = {{")
    for n in names:
        lines.append(f"    ICON_{n},")
    lines.append("};")
    lines.append("")
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines))


def main():
    arrays = []
    for name, fn in ICONS:
        path = os.path.join(SRC, fn)
        if not os.path.exists(path):
            print(f"[svg2icons] missing {path}", file=sys.stderr)
            return 1
        print(f"[svg2icons] {fn} -> ICON_{name} ({ICON_W}x{ICON_H})")
        arrays.append((name, rasterize(path)))
    emit(arrays)
    print(f"[svg2icons] wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
